/// Static catalogue of every operation per supported service.
///
/// Each entry maps a service slug to the full list of its AWS operations.
/// This drives the Operations tab in the Studio service explorer and lets
/// the UI show at-a-glance which operations have guided flows vs raw access.
use std::collections::HashMap;

use crate::guided_manifest::GuidedManifest;

/// A single operation offered by a service.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OperationEntry {
    /// AWS-style operation name, e.g. `"PutObject"`.
    pub name: String,
    /// HTTP method used for this operation.
    pub method: String,
    /// URL path template.
    pub path: String,
    /// Whether a guided flow covers this operation.
    pub has_guided_flow: bool,
}

/// All operations for one service.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ServiceOperationSet {
    pub service: String,
    pub operations: Vec<OperationEntry>,
}

impl ServiceOperationSet {
    pub fn guided_count(&self) -> usize {
        self.operations.iter().filter(|op| op.has_guided_flow).count()
    }

    pub fn total(&self) -> usize {
        self.operations.len()
    }
}

/// Full operation catalogue across all services, enriched with guided-flow
/// coverage from loaded manifests.
#[derive(Debug, Clone, Default)]
pub struct OperationCatalog {
    by_service: HashMap<String, ServiceOperationSet>,
}

impl OperationCatalog {
    /// Build from the built-in static operation list and optionally mark which
    /// operations have a corresponding guided manifest flow.
    pub fn build(manifests: &[GuidedManifest]) -> Self {
        let guided_index: HashMap<String, std::collections::HashSet<String>> = manifests
            .iter()
            .map(|m| {
                let ops: std::collections::HashSet<String> = m
                    .flows
                    .iter()
                    .flat_map(|f| f.steps.iter())
                    .map(|s| s.id.clone())
                    .collect();
                (m.service.clone(), ops)
            })
            .collect();

        let mut by_service: HashMap<String, ServiceOperationSet> = HashMap::new();

        for (service, raw_ops) in STATIC_OPERATIONS.iter() {
            let guided_ops = guided_index.get(*service);
            let operations = raw_ops
                .iter()
                .map(|(name, method, path)| OperationEntry {
                    name: name.to_string(),
                    method: method.to_string(),
                    path: path.to_string(),
                    has_guided_flow: guided_ops
                        .map(|set| set.contains(&name.to_lowercase()))
                        .unwrap_or(false),
                })
                .collect();

            by_service.insert(
                service.to_string(),
                ServiceOperationSet {
                    service: service.to_string(),
                    operations,
                },
            );
        }

        Self { by_service }
    }

    pub fn for_service(&self, service: &str) -> Option<&ServiceOperationSet> {
        self.by_service.get(service)
    }

    pub fn all_services(&self) -> impl Iterator<Item = &ServiceOperationSet> {
        self.by_service.values()
    }
}

/// Static operation list: (name, method, path).
/// Covers all 28 supported services.
static STATIC_OPERATIONS: &[(&str, &[(&str, &str, &str)])] = &[
    (
        "s3",
        &[
            ("CreateBucket", "PUT", "/{Bucket}"),
            ("DeleteBucket", "DELETE", "/{Bucket}"),
            ("ListBuckets", "GET", "/"),
            ("HeadBucket", "HEAD", "/{Bucket}"),
            ("GetBucketLocation", "GET", "/{Bucket}?location"),
            ("PutObject", "PUT", "/{Bucket}/{Key+}"),
            ("GetObject", "GET", "/{Bucket}/{Key+}"),
            ("DeleteObject", "DELETE", "/{Bucket}/{Key+}"),
            ("DeleteObjects", "POST", "/{Bucket}?delete"),
            ("HeadObject", "HEAD", "/{Bucket}/{Key+}"),
            ("CopyObject", "PUT", "/{Bucket}/{Key+}"),
            ("ListObjectsV2", "GET", "/{Bucket}?list-type=2"),
            ("ListObjects", "GET", "/{Bucket}"),
            ("ListObjectVersions", "GET", "/{Bucket}?versions"),
            ("CreateMultipartUpload", "POST", "/{Bucket}/{Key+}?uploads"),
            (
                "UploadPart",
                "PUT",
                "/{Bucket}/{Key+}?partNumber={PartNumber}&uploadId={UploadId}",
            ),
            (
                "CompleteMultipartUpload",
                "POST",
                "/{Bucket}/{Key+}?uploadId={UploadId}",
            ),
            (
                "AbortMultipartUpload",
                "DELETE",
                "/{Bucket}/{Key+}?uploadId={UploadId}",
            ),
            (
                "ListMultipartUploads",
                "GET",
                "/{Bucket}?uploads",
            ),
            ("PutBucketNotificationConfiguration", "PUT", "/{Bucket}?notification"),
            ("GetBucketNotificationConfiguration", "GET", "/{Bucket}?notification"),
            ("PutBucketVersioning", "PUT", "/{Bucket}?versioning"),
            ("GetBucketVersioning", "GET", "/{Bucket}?versioning"),
            ("PutBucketTagging", "PUT", "/{Bucket}?tagging"),
            ("GetBucketTagging", "GET", "/{Bucket}?tagging"),
            ("DeleteBucketTagging", "DELETE", "/{Bucket}?tagging"),
            ("PutObjectTagging", "PUT", "/{Bucket}/{Key+}?tagging"),
            ("GetObjectTagging", "GET", "/{Bucket}/{Key+}?tagging"),
            ("GetBucketPolicy", "GET", "/{Bucket}?policy"),
            ("PutBucketPolicy", "PUT", "/{Bucket}?policy"),
            ("DeleteBucketPolicy", "DELETE", "/{Bucket}?policy"),
            ("GetBucketCors", "GET", "/{Bucket}?cors"),
            ("PutBucketCors", "PUT", "/{Bucket}?cors"),
            ("DeleteBucketCors", "DELETE", "/{Bucket}?cors"),
            ("GetBucketWebsite", "GET", "/{Bucket}?website"),
            ("PutBucketWebsite", "PUT", "/{Bucket}?website"),
            ("DeleteBucketWebsite", "DELETE", "/{Bucket}?website"),
            ("GetBucketLifecycleConfiguration", "GET", "/{Bucket}?lifecycle"),
            ("PutBucketLifecycleConfiguration", "PUT", "/{Bucket}?lifecycle"),
            ("DeleteBucketLifecycle", "DELETE", "/{Bucket}?lifecycle"),
            ("GetBucketEncryption", "GET", "/{Bucket}?encryption"),
            ("PutBucketEncryption", "PUT", "/{Bucket}?encryption"),
            ("DeleteBucketEncryption", "DELETE", "/{Bucket}?encryption"),
            (
                "GetPresignedUrl",
                "GET",
                "/{Bucket}/{Key+}?X-Amz-Expires={Expires}",
            ),
        ],
    ),
    (
        "sqs",
        &[
            ("CreateQueue", "POST", "/"),
            ("DeleteQueue", "POST", "/"),
            ("ListQueues", "POST", "/"),
            ("GetQueueUrl", "POST", "/"),
            ("GetQueueAttributes", "POST", "/"),
            ("SetQueueAttributes", "POST", "/"),
            ("SendMessage", "POST", "/{QueueUrl}"),
            ("SendMessageBatch", "POST", "/{QueueUrl}"),
            ("ReceiveMessage", "POST", "/{QueueUrl}"),
            ("DeleteMessage", "POST", "/{QueueUrl}"),
            ("DeleteMessageBatch", "POST", "/{QueueUrl}"),
            ("ChangeMessageVisibility", "POST", "/{QueueUrl}"),
            ("ChangeMessageVisibilityBatch", "POST", "/{QueueUrl}"),
            ("PurgeQueue", "POST", "/{QueueUrl}"),
            ("AddPermission", "POST", "/{QueueUrl}"),
            ("RemovePermission", "POST", "/{QueueUrl}"),
            ("ListQueueTags", "POST", "/{QueueUrl}"),
            ("TagQueue", "POST", "/{QueueUrl}"),
            ("UntagQueue", "POST", "/{QueueUrl}"),
        ],
    ),
    (
        "sns",
        &[
            ("CreateTopic", "POST", "/"),
            ("DeleteTopic", "POST", "/"),
            ("ListTopics", "POST", "/"),
            ("GetTopicAttributes", "POST", "/"),
            ("SetTopicAttributes", "POST", "/"),
            ("Subscribe", "POST", "/"),
            ("Unsubscribe", "POST", "/"),
            ("ListSubscriptions", "POST", "/"),
            ("ListSubscriptionsByTopic", "POST", "/"),
            ("GetSubscriptionAttributes", "POST", "/"),
            ("SetSubscriptionAttributes", "POST", "/"),
            ("Publish", "POST", "/"),
            ("PublishBatch", "POST", "/"),
            ("ConfirmSubscription", "POST", "/"),
            ("ListTagsForResource", "POST", "/"),
            ("TagResource", "POST", "/"),
            ("UntagResource", "POST", "/"),
        ],
    ),
    (
        "dynamodb",
        &[
            ("CreateTable", "POST", "/"),
            ("DeleteTable", "POST", "/"),
            ("DescribeTable", "POST", "/"),
            ("ListTables", "POST", "/"),
            ("PutItem", "POST", "/"),
            ("GetItem", "POST", "/"),
            ("UpdateItem", "POST", "/"),
            ("DeleteItem", "POST", "/"),
            ("Query", "POST", "/"),
            ("Scan", "POST", "/"),
            ("BatchGetItem", "POST", "/"),
            ("BatchWriteItem", "POST", "/"),
            ("TransactGetItems", "POST", "/"),
            ("TransactWriteItems", "POST", "/"),
            ("UpdateTable", "POST", "/"),
            ("DescribeTimeToLive", "POST", "/"),
            ("UpdateTimeToLive", "POST", "/"),
            ("TagResource", "POST", "/"),
            ("UntagResource", "POST", "/"),
            ("ListTagsOfResource", "POST", "/"),
            ("DescribeContinuousBackups", "POST", "/"),
            ("UpdateContinuousBackups", "POST", "/"),
        ],
    ),
    (
        "lambda",
        &[
            ("CreateFunction", "POST", "/2015-03-31/functions"),
            ("DeleteFunction", "DELETE", "/2015-03-31/functions/{FunctionName}"),
            ("GetFunction", "GET", "/2015-03-31/functions/{FunctionName}"),
            ("ListFunctions", "GET", "/2015-03-31/functions"),
            ("InvokeFunction", "POST", "/2015-03-31/functions/{FunctionName}/invocations"),
            ("UpdateFunctionCode", "PUT", "/2015-03-31/functions/{FunctionName}/code"),
            ("UpdateFunctionConfiguration", "PUT", "/2015-03-31/functions/{FunctionName}/configuration"),
            ("GetFunctionConfiguration", "GET", "/2015-03-31/functions/{FunctionName}/configuration"),
            ("AddPermission", "POST", "/2015-03-31/functions/{FunctionName}/policy"),
            ("RemovePermission", "DELETE", "/2015-03-31/functions/{FunctionName}/policy/{StatementId}"),
            ("GetPolicy", "GET", "/2015-03-31/functions/{FunctionName}/policy"),
            ("CreateEventSourceMapping", "POST", "/2015-03-31/event-source-mappings"),
            ("ListEventSourceMappings", "GET", "/2015-03-31/event-source-mappings"),
            ("DeleteEventSourceMapping", "DELETE", "/2015-03-31/event-source-mappings/{UUID}"),
            ("GetEventSourceMapping", "GET", "/2015-03-31/event-source-mappings/{UUID}"),
            ("PublishVersion", "POST", "/2015-03-31/functions/{FunctionName}/versions"),
            ("ListVersionsByFunction", "GET", "/2015-03-31/functions/{FunctionName}/versions"),
            ("CreateAlias", "POST", "/2015-03-31/functions/{FunctionName}/aliases"),
            ("UpdateAlias", "PUT", "/2015-03-31/functions/{FunctionName}/aliases/{Name}"),
            ("DeleteAlias", "DELETE", "/2015-03-31/functions/{FunctionName}/aliases/{Name}"),
            ("ListAliases", "GET", "/2015-03-31/functions/{FunctionName}/aliases"),
            ("TagResource", "POST", "/2017-03-31/tags/{ARN}"),
            ("UntagResource", "DELETE", "/2017-03-31/tags/{ARN}"),
            ("ListTags", "GET", "/2017-03-31/tags/{ARN}"),
            ("GetFunctionConcurrency", "GET", "/2017-10-31/functions/{FunctionName}/concurrency"),
            ("PutFunctionConcurrency", "PUT", "/2017-10-31/functions/{FunctionName}/concurrency"),
            ("DeleteFunctionConcurrency", "DELETE", "/2017-10-31/functions/{FunctionName}/concurrency"),
        ],
    ),
    (
        "iam",
        &[
            ("CreateUser", "POST", "/"),
            ("DeleteUser", "POST", "/"),
            ("GetUser", "POST", "/"),
            ("ListUsers", "POST", "/"),
            ("CreateRole", "POST", "/"),
            ("DeleteRole", "POST", "/"),
            ("GetRole", "POST", "/"),
            ("ListRoles", "POST", "/"),
            ("AttachRolePolicy", "POST", "/"),
            ("DetachRolePolicy", "POST", "/"),
            ("ListAttachedRolePolicies", "POST", "/"),
            ("CreatePolicy", "POST", "/"),
            ("DeletePolicy", "POST", "/"),
            ("GetPolicy", "POST", "/"),
            ("ListPolicies", "POST", "/"),
            ("CreatePolicyVersion", "POST", "/"),
            ("GetPolicyVersion", "POST", "/"),
            ("ListPolicyVersions", "POST", "/"),
            ("DeletePolicyVersion", "POST", "/"),
            ("AttachUserPolicy", "POST", "/"),
            ("DetachUserPolicy", "POST", "/"),
            ("PutUserPolicy", "POST", "/"),
            ("GetUserPolicy", "POST", "/"),
            ("DeleteUserPolicy", "POST", "/"),
            ("ListUserPolicies", "POST", "/"),
            ("CreateAccessKey", "POST", "/"),
            ("DeleteAccessKey", "POST", "/"),
            ("ListAccessKeys", "POST", "/"),
            ("CreateGroup", "POST", "/"),
            ("DeleteGroup", "POST", "/"),
            ("GetGroup", "POST", "/"),
            ("ListGroups", "POST", "/"),
            ("AddUserToGroup", "POST", "/"),
            ("RemoveUserFromGroup", "POST", "/"),
            ("GetAccountSummary", "POST", "/"),
            ("GenerateCredentialReport", "POST", "/"),
            ("GetCredentialReport", "POST", "/"),
            ("SimulatePrincipalPolicy", "POST", "/"),
            ("CreateInstanceProfile", "POST", "/"),
            ("DeleteInstanceProfile", "POST", "/"),
            ("GetInstanceProfile", "POST", "/"),
            ("ListInstanceProfiles", "POST", "/"),
            ("AddRoleToInstanceProfile", "POST", "/"),
            ("RemoveRoleFromInstanceProfile", "POST", "/"),
            ("TagUser", "POST", "/"),
            ("UntagUser", "POST", "/"),
            ("ListUserTags", "POST", "/"),
            ("TagRole", "POST", "/"),
            ("UntagRole", "POST", "/"),
            ("ListRoleTags", "POST", "/"),
        ],
    ),
    (
        "kms",
        &[
            ("CreateKey", "POST", "/"),
            ("DescribeKey", "POST", "/"),
            ("ListKeys", "POST", "/"),
            ("ScheduleKeyDeletion", "POST", "/"),
            ("CancelKeyDeletion", "POST", "/"),
            ("EnableKey", "POST", "/"),
            ("DisableKey", "POST", "/"),
            ("Encrypt", "POST", "/"),
            ("Decrypt", "POST", "/"),
            ("ReEncrypt", "POST", "/"),
            ("GenerateDataKey", "POST", "/"),
            ("GenerateDataKeyWithoutPlaintext", "POST", "/"),
            ("GetKeyPolicy", "POST", "/"),
            ("PutKeyPolicy", "POST", "/"),
            ("ListKeyPolicies", "POST", "/"),
            ("CreateAlias", "POST", "/"),
            ("DeleteAlias", "POST", "/"),
            ("UpdateAlias", "POST", "/"),
            ("ListAliases", "POST", "/"),
            ("TagResource", "POST", "/"),
            ("UntagResource", "POST", "/"),
            ("ListResourceTags", "POST", "/"),
            ("GetKeyRotationStatus", "POST", "/"),
            ("EnableKeyRotation", "POST", "/"),
            ("DisableKeyRotation", "POST", "/"),
            ("Sign", "POST", "/"),
            ("Verify", "POST", "/"),
        ],
    ),
    (
        "kinesis",
        &[
            ("CreateStream", "POST", "/"),
            ("DeleteStream", "POST", "/"),
            ("DescribeStream", "POST", "/"),
            ("DescribeStreamSummary", "POST", "/"),
            ("ListStreams", "POST", "/"),
            ("PutRecord", "POST", "/"),
            ("PutRecords", "POST", "/"),
            ("GetRecords", "POST", "/"),
            ("GetShardIterator", "POST", "/"),
            ("ListShards", "POST", "/"),
            ("MergeShards", "POST", "/"),
            ("SplitShard", "POST", "/"),
            ("AddTagsToStream", "POST", "/"),
            ("RemoveTagsFromStream", "POST", "/"),
            ("ListTagsForStream", "POST", "/"),
            ("IncreaseStreamRetentionPeriod", "POST", "/"),
            ("DecreaseStreamRetentionPeriod", "POST", "/"),
            ("EnableEnhancedMonitoring", "POST", "/"),
            ("DisableEnhancedMonitoring", "POST", "/"),
            ("RegisterStreamConsumer", "POST", "/"),
            ("DeregisterStreamConsumer", "POST", "/"),
            ("ListStreamConsumers", "POST", "/"),
            ("DescribeStreamConsumer", "POST", "/"),
        ],
    ),
    (
        "events",
        &[
            ("CreateEventBus", "POST", "/"),
            ("DeleteEventBus", "POST", "/"),
            ("DescribeEventBus", "POST", "/"),
            ("ListEventBuses", "POST", "/"),
            ("PutRule", "POST", "/"),
            ("DeleteRule", "POST", "/"),
            ("DescribeRule", "POST", "/"),
            ("ListRules", "POST", "/"),
            ("EnableRule", "POST", "/"),
            ("DisableRule", "POST", "/"),
            ("PutTargets", "POST", "/"),
            ("RemoveTargets", "POST", "/"),
            ("ListTargetsByRule", "POST", "/"),
            ("PutEvents", "POST", "/"),
            ("ListTagsForResource", "POST", "/"),
            ("TagResource", "POST", "/"),
            ("UntagResource", "POST", "/"),
        ],
    ),
    (
        "secretsmanager",
        &[
            ("CreateSecret", "POST", "/"),
            ("DeleteSecret", "POST", "/"),
            ("DescribeSecret", "POST", "/"),
            ("GetSecretValue", "POST", "/"),
            ("ListSecrets", "POST", "/"),
            ("PutSecretValue", "POST", "/"),
            ("UpdateSecret", "POST", "/"),
            ("RotateSecret", "POST", "/"),
            ("RestoreSecret", "POST", "/"),
            ("TagResource", "POST", "/"),
            ("UntagResource", "POST", "/"),
            ("ListSecretVersionIds", "POST", "/"),
            ("GetResourcePolicy", "POST", "/"),
            ("PutResourcePolicy", "POST", "/"),
            ("DeleteResourcePolicy", "POST", "/"),
        ],
    ),
    (
        "ssm",
        &[
            ("PutParameter", "POST", "/"),
            ("GetParameter", "POST", "/"),
            ("GetParameters", "POST", "/"),
            ("GetParametersByPath", "POST", "/"),
            ("DeleteParameter", "POST", "/"),
            ("DeleteParameters", "POST", "/"),
            ("DescribeParameters", "POST", "/"),
            ("AddTagsToResource", "POST", "/"),
            ("RemoveTagsFromResource", "POST", "/"),
            ("ListTagsForResource", "POST", "/"),
            ("GetParameterHistory", "POST", "/"),
            ("LabelParameterVersion", "POST", "/"),
        ],
    ),
    (
        "states",
        &[
            ("CreateStateMachine", "POST", "/"),
            ("DeleteStateMachine", "POST", "/"),
            ("DescribeStateMachine", "POST", "/"),
            ("ListStateMachines", "POST", "/"),
            ("UpdateStateMachine", "POST", "/"),
            ("StartExecution", "POST", "/"),
            ("StopExecution", "POST", "/"),
            ("DescribeExecution", "POST", "/"),
            ("ListExecutions", "POST", "/"),
            ("GetExecutionHistory", "POST", "/"),
            ("StartSyncExecution", "POST", "/"),
            ("TagResource", "POST", "/"),
            ("UntagResource", "POST", "/"),
            ("ListTagsForResource", "POST", "/"),
        ],
    ),
    (
        "ec2",
        &[
            ("DescribeInstances", "POST", "/"),
            ("RunInstances", "POST", "/"),
            ("TerminateInstances", "POST", "/"),
            ("StartInstances", "POST", "/"),
            ("StopInstances", "POST", "/"),
            ("RebootInstances", "POST", "/"),
            ("DescribeImages", "POST", "/"),
            ("DescribeSecurityGroups", "POST", "/"),
            ("CreateSecurityGroup", "POST", "/"),
            ("DeleteSecurityGroup", "POST", "/"),
            ("AuthorizeSecurityGroupIngress", "POST", "/"),
            ("RevokeSecurityGroupIngress", "POST", "/"),
            ("DescribeVpcs", "POST", "/"),
            ("CreateVpc", "POST", "/"),
            ("DeleteVpc", "POST", "/"),
            ("DescribeSubnets", "POST", "/"),
            ("CreateSubnet", "POST", "/"),
            ("DeleteSubnet", "POST", "/"),
            ("DescribeKeyPairs", "POST", "/"),
            ("CreateKeyPair", "POST", "/"),
            ("DeleteKeyPair", "POST", "/"),
            ("DescribeVolumes", "POST", "/"),
            ("CreateVolume", "POST", "/"),
            ("DeleteVolume", "POST", "/"),
            ("AttachVolume", "POST", "/"),
            ("DetachVolume", "POST", "/"),
            ("AllocateAddress", "POST", "/"),
            ("ReleaseAddress", "POST", "/"),
            ("AssociateAddress", "POST", "/"),
            ("DescribeAddresses", "POST", "/"),
            ("CreateTags", "POST", "/"),
            ("DescribeTags", "POST", "/"),
            ("DeleteTags", "POST", "/"),
        ],
    ),
    (
        "ecr",
        &[
            ("CreateRepository", "POST", "/"),
            ("DeleteRepository", "POST", "/"),
            ("DescribeRepositories", "POST", "/"),
            ("ListImages", "POST", "/"),
            ("DescribeImages", "POST", "/"),
            ("BatchDeleteImage", "POST", "/"),
            ("BatchGetImage", "POST", "/"),
            ("PutImage", "POST", "/"),
            ("GetAuthorizationToken", "POST", "/"),
            ("InitiateLayerUpload", "POST", "/"),
            ("UploadLayerPart", "POST", "/"),
            ("CompleteLayerUpload", "POST", "/"),
            ("BatchCheckLayerAvailability", "POST", "/"),
            ("GetRepositoryPolicy", "POST", "/"),
            ("SetRepositoryPolicy", "POST", "/"),
            ("DeleteRepositoryPolicy", "POST", "/"),
            ("TagResource", "POST", "/"),
            ("UntagResource", "POST", "/"),
            ("ListTagsForResource", "POST", "/"),
        ],
    ),
    (
        "cloudwatch",
        &[
            ("PutMetricData", "POST", "/"),
            ("GetMetricData", "POST", "/"),
            ("GetMetricStatistics", "POST", "/"),
            ("ListMetrics", "POST", "/"),
            ("PutMetricAlarm", "POST", "/"),
            ("DeleteAlarms", "POST", "/"),
            ("DescribeAlarms", "POST", "/"),
            ("DescribeAlarmsForMetric", "POST", "/"),
            ("SetAlarmState", "POST", "/"),
            ("EnableAlarmActions", "POST", "/"),
            ("DisableAlarmActions", "POST", "/"),
            ("DescribeAlarmHistory", "POST", "/"),
            ("PutDashboard", "POST", "/"),
            ("GetDashboard", "POST", "/"),
            ("DeleteDashboards", "POST", "/"),
            ("ListDashboards", "POST", "/"),
            ("TagResource", "POST", "/"),
            ("UntagResource", "POST", "/"),
            ("ListTagsForResource", "POST", "/"),
        ],
    ),
    (
        "acm",
        &[
            ("RequestCertificate", "POST", "/"),
            ("DeleteCertificate", "POST", "/"),
            ("DescribeCertificate", "POST", "/"),
            ("ListCertificates", "POST", "/"),
            ("ImportCertificate", "POST", "/"),
            ("RenewCertificate", "POST", "/"),
            ("GetCertificate", "POST", "/"),
            ("AddTagsToCertificate", "POST", "/"),
            ("RemoveTagsFromCertificate", "POST", "/"),
            ("ListTagsForCertificate", "POST", "/"),
        ],
    ),
    (
        "sts",
        &[
            ("GetCallerIdentity", "POST", "/"),
            ("AssumeRole", "POST", "/"),
            ("AssumeRoleWithWebIdentity", "POST", "/"),
            ("AssumeRoleWithSAML", "POST", "/"),
            ("GetSessionToken", "POST", "/"),
            ("GetFederationToken", "POST", "/"),
            ("DecodeAuthorizationMessage", "POST", "/"),
        ],
    ),
    (
        "ses",
        &[
            ("SendEmail", "POST", "/"),
            ("SendRawEmail", "POST", "/"),
            ("SendTemplatedEmail", "POST", "/"),
            ("CreateTemplate", "POST", "/"),
            ("UpdateTemplate", "POST", "/"),
            ("DeleteTemplate", "POST", "/"),
            ("GetTemplate", "POST", "/"),
            ("ListTemplates", "POST", "/"),
            ("VerifyEmailIdentity", "POST", "/"),
            ("DeleteIdentity", "POST", "/"),
            ("ListIdentities", "POST", "/"),
            ("GetIdentityVerificationAttributes", "POST", "/"),
            ("SetIdentityFeedbackForwardingEnabled", "POST", "/"),
            ("SetIdentityNotificationTopic", "POST", "/"),
            ("GetSendQuota", "POST", "/"),
            ("GetSendStatistics", "POST", "/"),
        ],
    ),
    (
        "route53",
        &[
            ("CreateHostedZone", "POST", "/2013-04-01/hostedzone"),
            ("DeleteHostedZone", "DELETE", "/2013-04-01/hostedzone/{Id}"),
            ("GetHostedZone", "GET", "/2013-04-01/hostedzone/{Id}"),
            ("ListHostedZones", "GET", "/2013-04-01/hostedzone"),
            ("ListHostedZonesByName", "GET", "/2013-04-01/hostedzonesbyname"),
            ("ChangeResourceRecordSets", "POST", "/2013-04-01/hostedzone/{Id}/rrset"),
            ("ListResourceRecordSets", "GET", "/2013-04-01/hostedzone/{Id}/rrset"),
            ("GetChange", "GET", "/2013-04-01/change/{Id}"),
            ("CreateHealthCheck", "POST", "/2013-04-01/healthcheck"),
            ("DeleteHealthCheck", "DELETE", "/2013-04-01/healthcheck/{HealthCheckId}"),
            ("GetHealthCheck", "GET", "/2013-04-01/healthcheck/{HealthCheckId}"),
            ("ListHealthChecks", "GET", "/2013-04-01/healthcheck"),
            ("ListTagsForResource", "GET", "/2013-04-01/tags/{ResourceType}/{ResourceId}"),
            ("ChangeTagsForResource", "POST", "/2013-04-01/tags/{ResourceType}/{ResourceId}"),
        ],
    ),
    (
        "redshift",
        &[
            ("CreateCluster", "POST", "/"),
            ("DeleteCluster", "POST", "/"),
            ("DescribeClusters", "POST", "/"),
            ("ModifyCluster", "POST", "/"),
            ("RebootCluster", "POST", "/"),
            ("PauseCluster", "POST", "/"),
            ("ResumeCluster", "POST", "/"),
            ("CreateClusterSubnetGroup", "POST", "/"),
            ("DeleteClusterSubnetGroup", "POST", "/"),
            ("DescribeClusterSubnetGroups", "POST", "/"),
            ("CreateClusterParameterGroup", "POST", "/"),
            ("DeleteClusterParameterGroup", "POST", "/"),
            ("DescribeClusterParameterGroups", "POST", "/"),
            ("CreateClusterSnapshot", "POST", "/"),
            ("DeleteClusterSnapshot", "POST", "/"),
            ("DescribeClusterSnapshots", "POST", "/"),
            ("RestoreFromClusterSnapshot", "POST", "/"),
            ("CreateTags", "POST", "/"),
            ("DeleteTags", "POST", "/"),
            ("DescribeTags", "POST", "/"),
        ],
    ),
    (
        "opensearch",
        &[
            ("CreateDomain", "POST", "/2021-01-01/opensearch/domain"),
            ("DeleteDomain", "DELETE", "/2021-01-01/opensearch/domain/{DomainName}"),
            ("DescribeDomain", "GET", "/2021-01-01/opensearch/domain/{DomainName}"),
            ("ListDomainNames", "GET", "/2021-01-01/opensearch/domain"),
            ("UpdateDomainConfig", "POST", "/2021-01-01/opensearch/domain/{DomainName}/config"),
            ("DescribeDomainConfig", "GET", "/2021-01-01/opensearch/domain/{DomainName}/config"),
            ("DescribeDomainHealth", "GET", "/2021-01-01/opensearch/domain/{DomainName}/health"),
            ("AddTags", "POST", "/2021-01-01/tags"),
            ("RemoveTags", "POST", "/2021-01-01/tags-removal"),
            ("ListTags", "GET", "/2021-01-01/tags/{ARN}"),
        ],
    ),
    (
        "cloudformation",
        &[
            ("CreateStack", "POST", "/"),
            ("DeleteStack", "POST", "/"),
            ("DescribeStacks", "POST", "/"),
            ("DescribeStackResource", "POST", "/"),
            ("DescribeStackResources", "POST", "/"),
            ("ListStacks", "POST", "/"),
            ("ListStackResources", "POST", "/"),
            ("UpdateStack", "POST", "/"),
            ("ValidateTemplate", "POST", "/"),
            ("GetTemplate", "POST", "/"),
            ("GetTemplateSummary", "POST", "/"),
            ("CreateChangeSet", "POST", "/"),
            ("ExecuteChangeSet", "POST", "/"),
            ("DeleteChangeSet", "POST", "/"),
            ("DescribeChangeSet", "POST", "/"),
            ("ListChangeSets", "POST", "/"),
            ("SetStackPolicy", "POST", "/"),
            ("GetStackPolicy", "POST", "/"),
        ],
    ),
    (
        "apigateway",
        &[
            ("CreateRestApi", "POST", "/restapis"),
            ("DeleteRestApi", "DELETE", "/restapis/{restapi_id}"),
            ("GetRestApis", "GET", "/restapis"),
            ("GetRestApi", "GET", "/restapis/{restapi_id}"),
            ("CreateResource", "POST", "/restapis/{restapi_id}/resources/{parent_id}"),
            ("GetResources", "GET", "/restapis/{restapi_id}/resources"),
            ("GetResource", "GET", "/restapis/{restapi_id}/resources/{resource_id}"),
            ("DeleteResource", "DELETE", "/restapis/{restapi_id}/resources/{resource_id}"),
            ("PutMethod", "PUT", "/restapis/{restapi_id}/resources/{resource_id}/methods/{http_method}"),
            ("PutIntegration", "PUT", "/restapis/{restapi_id}/resources/{resource_id}/methods/{http_method}/integration"),
            ("CreateDeployment", "POST", "/restapis/{restapi_id}/deployments"),
            ("GetDeployments", "GET", "/restapis/{restapi_id}/deployments"),
            ("CreateStage", "POST", "/restapis/{restapi_id}/stages"),
            ("GetStages", "GET", "/restapis/{restapi_id}/stages"),
            ("DeleteStage", "DELETE", "/restapis/{restapi_id}/stages/{stage_name}"),
            ("CreateApiKey", "POST", "/apikeys"),
            ("GetApiKeys", "GET", "/apikeys"),
            ("DeleteApiKey", "DELETE", "/apikeys/{api_Key}"),
            ("CreateUsagePlan", "POST", "/usageplans"),
            ("GetUsagePlans", "GET", "/usageplans"),
        ],
    ),
    (
        "firehose",
        &[
            ("CreateDeliveryStream", "POST", "/"),
            ("DeleteDeliveryStream", "POST", "/"),
            ("DescribeDeliveryStream", "POST", "/"),
            ("ListDeliveryStreams", "POST", "/"),
            ("PutRecord", "POST", "/"),
            ("PutRecordBatch", "POST", "/"),
            ("UpdateDestination", "POST", "/"),
            ("StartDeliveryStreamEncryption", "POST", "/"),
            ("StopDeliveryStreamEncryption", "POST", "/"),
            ("TagDeliveryStream", "POST", "/"),
            ("UntagDeliveryStream", "POST", "/"),
            ("ListTagsForDeliveryStream", "POST", "/"),
        ],
    ),
];
